services:
  - type: web
    name: chat-realtime-api
    env: docker
    plan: free
    repo: https://github.com/toanphangl1997/Chat-RealTime-BE
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chat-realtime-db
          property: connectionString
      - key: JWT_SECRET
        value: your_jwt_secret_here

databases:
  - name: chat-realtime-db
    plan: free
    databaseName: chat_app
    user: chat_user
